#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: General setup for all
  hosts: [controller, data_node, client]
  connection: ssh
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: Install packages
      become: true
      apt: pkg={{ item }} state=present
      with_items:
        - wget
        - tuned
        - openjdk-17-jdk
        - sysstat
        - vim
        - chrony
    - name: Set common facts
      set_fact:
        controllerServers: "{{ groups['controller'] | map('extract', hostvars, ['private_ip']) | map('regex_replace', '^(.*)$', '\\1:9093') | join(',') }}"
        brokerServers: "{{ groups['data_node'] | map('extract', hostvars, ['private_ip']) | map('regex_replace', '^(.*)$', '\\1:9092') | join(',') }}"
        privateIp: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    - name: Change locale to en_US.utf-8
      become: true
      shell: |
        echo 'LANG=en_US.utf-8
              LC_ALL=en_US.utf-8' > /etc/environment
    - name: set facts for kafka
      set_fact:
        connect_pm_addresses: "{{ groups['placement_manager'] | map('extract', hostvars, 'private_ip') | list }}"
        stream_replication: 1


- name: Deploy a es cluster
 ansible.builtin.import_playbook: es-deploy.yaml

- name: Format and mount disks for Kafka hosts
  hosts: [controller] # skip  data_node
  connection: ssh
  become: true
  tasks:
    - command: >
        tuned-adm profile latency-performance
    - name: Format disks
      filesystem:
        fstype: xfs
        dev: '{{ item }}'
      with_items:
        - '/dev/nvme1n1'
    - name: Mount disks
      mount:
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        fstype: xfs
        opts: defaults,noatime,nodiscard
        state: mounted
      with_items:
        - { path: "/mnt/data-1", src: "/dev/nvme1n1" }
    - name: Increase hard file descriptor limit
      pam_limits:
        domain: '*'
        limit_type: 'hard'
        limit_item: nofile
        value: 500000
    - name: Increase soft file descriptor limit
      pam_limits:
        domain: '*'
        limit_type: 'soft'
        limit_item: nofile
        value: 500000
    - name: Enable pam_limits.so
      lineinfile:
        path: /etc/pam.d/login
        insertafter: EOF
        line: 'session required pam_limits.so'
    - name: set vm.max_map_count
      sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present
        reload: yes
    - name: Reboot the machine with all defaults
      reboot:

- name: Kafka general setup
  hosts: [controller, data_node]
  connection: ssh
  tasks:
    # used for building kafka
    - name: Install Rust and Cargo
      tags: [rust, dependencies]
      block:
        - name: Download Rust installer
          get_url:
            url: https://sh.rustup.rs
            dest: /tmp/sh.rustup.rs
            mode: '0755'
            force: 'yes'
        - name: Install Rust and Cargo
          command: /tmp/sh.rustup.rs --verbose -y --default-toolchain nightly
        - shell: source $HOME/.cargo/env && cargo --version
          args:
            executable: /bin/bash
          register: cargo_version
        - debug:
            var: cargo_version.stdout
    - name: Install dependencies
      tags: [dependencies]
      block:
        - name: Install apt packages
          become: true
          apt:
            name: "{{ item }}"
            state: present
          with_items:
            - build-essential
            - clang
            - unzip
            - maven
        - name: Install flatc
          become: true
          unarchive:
            src: https://github.com/google/flatbuffers/releases/download/v23.3.3/Linux.flatc.binary.g++-10.zip
            dest: /usr/local/bin
            remote_src: yes
        - shell: flatc --version
          register: flatc_version
        - debug:
            var: flatc_version.stdout
    - name: Clone latest es code from github
      tags: [git, build]
      git:
        repo: https://github.com/AutoMQ/elastic-stream.git
        dest: /home/ubuntu/elastic-stream-dn
        version: develop
        depth: 1
        single_branch: true
        force: true
    - name: Build java sdk
      tags: [sdk, build]
      shell: |
        source $HOME/.cargo/env
        ./build.sh
      args:
        chdir: /home/ubuntu/elastic-stream-dn/sdks
        executable: /bin/bash
    - name: install java sdk
      tags: [sdk, install]
      shell: |
        mvn install -DskipTests -DskipSigning
      args:
        chdir: /home/ubuntu/elastic-stream-dn/sdks/frontend-java
    - name: change opt owner
      become: true
      file:
        path: /opt
        owner: ubuntu
        group: ubuntu
        mode: 0777
    - name: Clone latest kafka code from github
      tags: [ git, build ]
      git:
        repo: https://github.com/AutoMQ/kafka.git
        dest: /opt/kafka
        version: develop
        depth: 1
        single_branch: true
        force: true
    - name: create gradle directory
      file:
        path: /home/ubuntu/.gradle
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755
    - name: Setting gradle properties
      copy:
        src: templates/init.gradle
        dest: /home/ubuntu/.gradle/init.gradle
    - name: Build kafka
      tags: [ kafka, build ]
      shell: |
        ./gradlew jar -x test
      args:
        chdir: /opt/kafka
        executable: /bin/bash

    - name: Generate quorum servers
      set_fact:
        quorumServers: "{{ quorumServers | default('') + (itemIndex + 1) | string + '@' + item + ',' }}"
      loop: "{{ groups['controller'] | map('extract', hostvars, ['private_ip']) | map('regex_replace', '^(.*)$', '\\1:9093') }}"
      loop_control:
        index_var: itemIndex
    - name: Set common facts
      set_fact:
        quorumServers: "{{ quorumServers[:-1] }}"
        kafkaVersion: "3.4.0"
        KAFKA_CLUSTER_ID: "XPufKTN9T1SpE82LDKwXwA"

# setting controllers.
- name: Setup Kafka controllers
  hosts: controller
  connection: ssh
  tasks:
    - name: Set nodeId
      set_fact:
        nodeId: "{{ groups['controller'].index(inventory_hostname) + 1 }}"
    - template:
        src: "templates/controller.properties"
        dest: "/opt/kafka/config/kraft/controller.properties"
    - become: true
      template:
        src: "templates/controller.service"
        dest: "/etc/systemd/system/controller.service"
    # - name: Format Log Directories
    #   shell: bin/kafka-storage.sh format -t {{ KAFKA_CLUSTER_ID }} -c config/kraft/controller.properties
    #   args:
    #     chdir: /opt/kafka/
    - become: true
      systemd:
        state: restarted
        daemon_reload: yes
        name: "controller"
      tags: [restart-controller]


- name: Setup Kafka brokers
  hosts: data_node
  connection: ssh
  tasks:
    - name: Set nodeId
      set_fact:
        nodeId: "{{  (groups['controller'] | length) + groups['data_node'].index(inventory_hostname) + 1 }}"
    - name: Set up broker
      template:
        src: "templates/broker.properties"
        dest: "/opt/kafka/config/kraft/broker.properties"
    - become: true
      template:
        src: "templates/broker.service"
        dest: "/etc/systemd/system/broker.service"
    - name: Format Log Directories
      shell: bin/kafka-storage.sh format -t {{ KAFKA_CLUSTER_ID }} -c config/kraft/broker.properties
      args:
        chdir: /opt/kafka/
    - become: true
      systemd:
        state: restarted
        daemon_reload: yes
        name: "broker"
      tags: [restart-broker]


- name: Setup Benchmark client
  hosts: client
  connection: ssh
  tasks:
    - file: path=/opt/benchmark state=absent
      tags: [client-code]
    - name: change opt owner
      become: true
      file:
        path: /opt
        owner: ubuntu
        group: ubuntu
        mode: 0777
    - name: Copy benchmark code
      unarchive:
        src: ../../package/target/openmessaging-benchmark-0.0.1-SNAPSHOT-bin.tar.gz
        dest: /opt
      tags: [client-code]
    - shell: mv /opt/openmessaging-benchmark-0.0.1-SNAPSHOT /opt/benchmark
      tags: [client-code]
    - become: true
      shell: tuned-adm profile latency-performance

    - name: Get list of driver config files
      raw: ls -1 /opt/benchmark/driver-kafka/*.yaml
      register: drivers_list
      tags: [client-code]

    - name: Configure Bootstrap Servers
      lineinfile:
        dest: '{{ item }}'
        regexp: '^  bootstrap.servers='
        line: '  bootstrap.servers={{ brokerServers }}'
      with_items: '{{ drivers_list.stdout_lines }}'
      tags: [client-code]

    - name: Get list of jms driver config files
      raw: ls -1 /opt/benchmark/driver-jms/kafka*.yaml
      register: jms_drivers_list

    - name: Configure JMS Bootstrap Servers
      lineinfile:
        dest: '{{ item }}'
        regexp: '^  bootstrap.servers='
        line: '  bootstrap.servers={{ brokerServers }}'
      with_items: '{{ jms_drivers_list.stdout_lines }}'

    - name: Configure JMS Connection Factory
      ansible.builtin.replace:
        dest: '{{ item }}'
        regexp: 'localhost\:9092'
        replace: '{{ brokerServers }}'
      with_items: '{{ jms_drivers_list.stdout_lines }}'

    - name: Configure memory
      lineinfile:
        dest: /opt/benchmark/bin/benchmark-worker
        regexp: '^JVM_MEM='
        line: 'JVM_MEM="-Xms100G -Xmx100G -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:+ParallelRefProcEnabled -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=12 -XX:ConcGCThreads=12 -XX:+DisableExplicitGC -XX:-ResizePLAB"'
      tags: [client-code]
    - name: Configure memory
      lineinfile:
        dest: /opt/benchmark/bin/benchmark
        regexp: '^JVM_MEM='
        line: 'JVM_MEM="-Xmx4G"'
      tags: [client-code]
    - template:
        src: "templates/workers.yaml"
        dest: "/opt/benchmark/workers.yaml"
      tags: [client-code]
    - name: Install benchmark systemd service
      become: true
      template:
        src: "templates/benchmark-worker.service"
        dest: "/etc/systemd/system/benchmark-worker.service"
      tags: [client-code]
    - become: true
      systemd:
        state: restarted
        daemon_reload: yes
        name: "benchmark-worker"
      tags: [client-code]

    - name: Set up chronyd
      become: true
      template:
        src: "templates/chrony.conf"
        dest: "/etc/chrony.conf"
    - become: true
      systemd:
        state: restarted
        daemon_reload: yes
        name: "chronyd"


- name:  Hosts addresses
  hosts: localhost
  tasks:
    - debug:
        msg: "Kafka controller servers {{ item }}"
      with_items: "{{ groups['controller'] }}"
    - debug:
        msg: "Kafka brokers {{ item }}"
      with_items: "{{ groups['data_node'] }}"
    - debug:
        msg: "Benchmark clients {{ item }}"
      with_items: "{{ groups['client'] }}"

