{
 "title": "automq-for-kafka",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "label": "cluster_id",
    "query": {
     "query": "label_values(default_jvm_cpu_recent_utilization_ratio,service_namespace)"
    }
   },
   { "name": "namespace", "query": "default" },
   { "name": "prefix", "query": "kafka_stream" },
   { "name": "OperationType", "query": "S3Stream,S3Storage,S3Request" },
   {
    "name": "node_id",
    "query": {
     "query": "label_values(default_jvm_cpu_recent_utilization_ratio,service_instance_id)"
    }
   },
   {
    "name": "node_type",
    "query": {
     "query": "label_values(default_jvm_cpu_recent_utilization_ratio,service_name)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "default_jvm_cpu_recent_utilization_ratio{service_namespace=\"$cluster_id\", service_name=~\"$node_type\", service_instance_id=~\"$node_id\"}",
     "legendFormat": "{{service_name}}_{{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(service_namespace, service_name, service_instance_id) (default_jvm_memory_used_bytes{service_namespace=\"$cluster_id\", service_name=~\"$node_type\", service_instance_id=~\"$node_id\"})",
     "legendFormat": "{{service_name}}_{{service_instance_id}}"
    },
    { "expression": "$B/$A\n", "type": "math" }
   ]
  },
  {
   "title": "JVM GC Monitor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, service_name, service_instance_id, jvm_gc_action) (rate(default_jvm_gc_duration_seconds_bucket{service_namespace=\"$cluster_id\", service_name=~\"$node_type\", service_instance_id=~\"$node_id\"}[$__rate_interval])))",
     "legendFormat": "{{service_name}}_{{service_instance_id}}_{{jvm_gc_action}}"
    },
    {
     "expr": "sum by(jvm_gc_action, service_name, service_instance_id) (rate(default_jvm_gc_duration_seconds_count{service_namespace=\"$cluster_id\", service_name=~\"$node_type\", service_instance_id=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}_{{service_instance_id}}_{{jvm_gc_action}}"
    }
   ]
  },
  { "title": "S3Stream Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "S3Stream Operation Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(operation_name, operation_type) (rate(${namespace}_${prefix}_operation_latency_nanoseconds_count{operation_type=~\"$OperationType\", operation_name!~\"append_wal|read_block_cache|read_log_cache\", cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval]))",
     "legendFormat": "{{operation_type}}_{{operation_name}}"
    }
   ]
  },
  {
   "title": "S3Stream Operation Status Distribution",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 10, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (${namespace}_${prefix}_operation_latency_nanoseconds_count{operation_type=\"S3Request\", operation_name=~\".*\", cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\", status=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3Stream Operation Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation_type, operation_name) (rate(${namespace}_${prefix}_operation_latency_nanoseconds_bucket{operation_type=~\"$OperationType\", operation_name!~\"append_wal|read_block_cache|read_log_cache\", cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "{{operation_type}}_{{operation_name}}"
    }
   ]
  },
  { "title": "Delta WAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Append Delta WAL Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(${namespace}_${prefix}_operation_latency_nanoseconds_count{operation_type=\"S3Storage\", operation_name=~\"append_log_cache|append_callback|append_wal_full\", cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])",
     "legendFormat": "{{operation_name}}"
    },
    {
     "expr": "rate(${namespace}_${prefix}_operation_latency_nanoseconds_count{operation_type=\"S3Storage\", operation_name=~\"append_wal\", stage=~\".*\", cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])",
     "legendFormat": "{{operation_name}}_{{stage}}"
    },
    {
     "expr": "rate(${namespace}_${prefix}_operation_count_total{operation_type=\"S3Storage\", operation_name=\"append_log_cache_full\", cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])",
     "legendFormat": "{{operation_name}}"
    }
   ]
  },
  {
   "title": "Append Delta WAL Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation_type, operation_name, stage) (rate(${namespace}_${prefix}_operation_latency_nanoseconds_bucket{operation_type=\"S3Storage\", operation_name=\"append_wal\", stage=~\".*\", cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "{{operation_name}}_{{stage}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation_type, operation_name) (rate(${namespace}_${prefix}_operation_latency_nanoseconds_bucket{operation_type=\"S3Storage\", operation_name=~\"append_callback|append_log_cache\"}[$__rate_interval])))",
     "legendFormat": "{{operation_name}}"
    }
   ]
  },
  {
   "title": "Read Delta WAL Cache Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "rate(${namespace}_${prefix}_operation_latency_nanoseconds_count{operation_type=\"S3Storage\", operation_name=~\"read_log_cache\", status=~\".*\", cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])",
     "legendFormat": "{{operation_name}}_{{status}}"
    }
   ]
  },
  {
   "title": "Read Delta WAL Cache Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation_type, operation_name, status) (rate(${namespace}_${prefix}_operation_latency_nanoseconds_bucket{operation_type=\"S3Storage\", operation_name=~\"read_log_cache\", status=~\".*\", cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "{{operation_name}}_{{status}}"
    }
   ]
  },
  {
   "title": "Delta WAL Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expression": "$A - $B", "type": "math" },
    {
     "expr": "default_kafka_stream_delta_wal_cache_size_bytes{cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}",
     "legendFormat": "delta wal cache"
    }
   ]
  },
  { "title": "Block Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Read Block Cache Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "rate(${namespace}_${prefix}_operation_latency_nanoseconds_count{operation_type=\"S3Storage\", operation_name=\"read_block_cache\", status=~\".*\", cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])",
     "legendFormat": "{{operation_name}}_{{status}}"
    }
   ]
  },
  {
   "title": "Read Block Cache Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation_type, operation_name, status) (rate(${namespace}_${prefix}_operation_latency_nanoseconds_bucket{operation_type=\"S3Storage\", operation_name=\"read_block_cache\", status=~\".*\", cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "{{operation_name}}_{{status}}"
    }
   ]
  },
  {
   "title": "Block Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "${namespace}_${prefix}_block_cache_size_bytes{cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Read Ahead Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation_type, operation_name, status) (rate(${namespace}_${prefix}_operation_latency_nanoseconds_bucket{operation_type=\"S3Storage\", operation_name=\"read_ahead\", status=~\".*\", cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "{{operation_name}}_{{status}}"
    }
   ]
  },
  { "title": "Networks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "S3Stream Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(${namespace}_${prefix}_network_inbound_usage_bytes_total{cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])",
     "legendFormat": "inbound"
    },
    {
     "expr": "rate(${namespace}_${prefix}_network_outbound_usage_bytes_total{cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "S3 Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(${namespace}_${prefix}_download_size_bytes_total{cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])",
     "legendFormat": "download"
    },
    {
     "expr": "rate(${namespace}_${prefix}_upload_size_bytes_total{cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])",
     "legendFormat": "upload"
    }
   ]
  },
  {
   "title": "S3Stream Network Available Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "${namespace}_${prefix}_network_inbound_available_bandwidth_bytes{cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}",
     "legendFormat": "inbound"
    },
    {
     "expr": "${namespace}_${prefix}_network_outbound_available_bandwidth_bytes{cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "S3 Network Limiter",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "${namespace}_${prefix}_network_inbound_limiter_queue_size{cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}",
     "legendFormat": "inbound"
    },
    {
     "expr": "${namespace}_${prefix}_network_outbound_limiter_queue_size{cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "Available S3 Inflight Quota",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "${namespace}_${prefix}_available_s3_inflight_read_quota{cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}",
     "legendFormat": "read"
    },
    {
     "expr": "${namespace}_${prefix}_available_s3_inflight_write_quota{cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "S3Stream Network Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, cluster_id, node_id, node_type) (rate(${namespace}_${prefix}_network_inbound_limiter_queue_time_nanoseconds_bucket{cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "inbound"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, cluster_id, node_id, node_type) (rate(${namespace}_${prefix}_network_outbound_limiter_queue_time_nanoseconds_bucket{cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "outbound"
    }
   ]
  },
  { "title": "S3 Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "S3 Object Count Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 133 },
   "targets": [
    {
     "expr": "rate(${namespace}_${prefix}_object_count_total{cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])",
     "legendFormat": "object_count"
    }
   ]
  },
  {
   "title": "Upload S3 Object Stage Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(stage, le) (rate(${namespace}_${prefix}_object_stage_cost_nanoseconds_bucket{stage=~\".*\", cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Get Object Size Distribution",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 3, "x": 0, "y": 147 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(size) (${namespace}_${prefix}_operation_latency_nanoseconds_count{operation_type=\"S3Request\", operation_name=\"get_object\", cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GetObject Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 9, "x": 3, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation_type, operation_name, size) (rate(${namespace}_${prefix}_operation_latency_nanoseconds_bucket{operation_type=\"S3Request\", operation_name=\"get_object\", size=~\".*\", cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "{{size}}"
    }
   ]
  },
  {
   "title": "Upload Object Size Distribution",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 3, "x": 12, "y": 147 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(size) (${namespace}_${prefix}_operation_latency_nanoseconds_count{operation_type=\"S3Request\", operation_name=~\"put_object|upload_part\", cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"})",
     "legendFormat": "{{size}}"
    }
   ]
  },
  {
   "title": "Upload Object Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, size) (rate(${namespace}_${prefix}_operation_latency_nanoseconds_bucket{operation_type=\"S3Request\", operation_name=~\"put_object|upload_part\", size=~\".*\", cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "{{size}}"
    }
   ]
  },
  { "title": "Compaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 } },
  {
   "title": "Compaction Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(${namespace}_${prefix}_compaction_read_size_bytes_total{cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])",
     "legendFormat": "compaction_read"
    },
    {
     "expr": "rate(${namespace}_${prefix}_compaction_write_size_bytes_total{cluster_id=\"$cluster_id\", node_id=\"$node_id\", node_type=\"$node_type\"}[$__rate_interval])",
     "legendFormat": "compaction_write"
    }
   ]
  }
 ]
}